# Ruby CircleCI 2.0 configuration file
#
version: 2
jobs:
  build:
    docker:
      - image: spittet/ruby-mysql

    environment:
      COVERALLS_REPO_TOKEN: coverallsRepoToken

    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: upgrade bundler
          command:
            gem install bundler -v 1.16.1

      - run:
          name: install dependencies
          command:
            bundle install --jobs=4 --retry=3 --path vendor/bundle

      # Database setup
      - run:
          name: start mysql
          command:
            /etc/init.d/mysql start

      - run: bundle exec rake db:create

      # run tests!
      - run:
          name: run tests
          command:
            COVERALLS_REPO_TOKEN=$COVERALLS_REPO_TOKEN rake test

      - run:
          name: get coverage
          command:
            coverage xml

      - run:
          name: push result data to coveralls
          command:
            bundle exec rake coveralls:push

      - store_test_results:
          path: tmp/test-results

      - store_artifacts:
          path: tmp/test-results
          destination: test-results